apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"httpd.saberkan.fr/v1","kind":"Httpd","metadata":{"name":"example-httpd"},"spec":{"size":3}}]'
    capabilities: Basic Install
  name: httpd-operator.v1.0.0
  namespace: operators-olm
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: httpd
      name: httpds.httpd.saberkan.fr
      version: v1
      displayName: httpd
      description: my httpd
  minKubeVersion: 1.11.1
  description: This is my csv for httpd operator
  displayName: Httpd Operator
  install:
    spec:
      deployments:
      - name: httpd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: httpd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: httpd-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/saberkan/httpd-operator:v1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: httpd-operator
                image: quay.io/saberkan/httpd-operator:v1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: httpd-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          - route.openshift.io
          - apps.openshift.io
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - httpd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - httpd.saberkan.fr
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: httpd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 1.0.0
