apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httpds.httpd.saberkan.fr
spec:
  group: httpd.saberkan.fr
  names:
    kind: Httpd
    listKind: HttpdList
    plural: httpds
    singular: httpd
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
